### PR TITLE
builtin.c: typecheck builtin cfunctions in function_list

### LINKED ISSUE #3206: Build failure with GCC 15 (C23)
**Describe the bug**
jq fails to build with upcoming GCC 15 that defaults to C23. This can be reproduced on older GCC and Clang versions by adding `-std=gnu23` to CFLAGS.

Downstream Gentoo bug: https://bugs.gentoo.org/944014

**Environment (please complete the following information):**

- OS: Gentoo Linux
- jq version: happens with both master and 1.7.1

```
src/builtin.c:1794:4: error: initialization of 'jv (*)(void)' from incompatible pointer type 'jv (*)(jq_state *, jv)' [-Wincompatible-pointer-types]
 1794 |   {f_ ## name, #name, 1},
      |    ^~
src/libm.h:2:1: note: in expansion of macro 'LIBM_DD'
    2 | LIBM_DD(acos)
      | ^~~~~~~
src/builtin.c:1794:4: note: (near initialization for 'function_list[0].fptr')
 1794 |   {f_ ## name, #name, 1},
      |    ^~
src/builtin.c:1800:4: error: initialization of 'jv (*)(void)' from incompatible pointer type 'jv (*)(jq_state *, jv,  jv,  jv)' [-Wincompatible-pointer-types]
 1800 |   {f_ ## name, #name, 3},
      |    ^~
src/libm.h:27:1: note: in expansion of macro 'LIBM_DDD'
   27 | LIBM_DDD(atan2)
      | ^~~~~~~~
src/builtin.c:1800:4: note: (near initialization for 'function_list[5].fptr')
 1800 |   {f_ ## name, #name, 3},
      |    ^~
src/libm.h:27:1: note: in expansion of macro 'LIBM_DDD'
   27 | LIBM_DDD(atan2)
      | ^~~~~~~~
src/builtin.c:1809:4: error: initialization of 'jv (*)(void)' from incompatible pointer type 'jv (*)(jq_state *, jv)' [-Wincompatible-pointer-types]
 1809 |   {f_negate, "_negate", 1},
      |    ^~~~~~~~
src/builtin.c:1809:4: note: (near initialization for 'function_list[61].fptr')
src/builtin.c:1810:22: error: initialization of 'jv (*)(void)' from incompatible pointer type 'jv (*)(jq_state *, jv,  jv,  jv)' [-Wincompatible-pointer-types]
 1810 | #define BINOP(name) {f_ ## name, "_" #name, 3},
      |                      ^~
src/builtin.h:11:3: note: in expansion of macro 'BINOP'
   11 |   BINOP(plus) \
      |   ^~~~~
src/builtin.c:1811:1: note: in expansion of macro 'BINOPS'
 1811 | BINOPS
      | ^~~~~~
src/builtin.c:1810:22: note: (near initialization for 'function_list[62].fptr')
 1810 | #define BINOP(name) {f_ ## name, "_" #name, 3},
      |                      ^~
src/builtin.h:11:3: note: in expansion of macro 'BINOP'
   11 |   BINOP(plus) \
      |   ^~~~~
src/builtin.c:1811:1: note: in expansion of macro 'BINOPS'
 1811 | BINOPS
      | ^~~~~~
```

Above are just some of the errors the rest are in the build log that's attached
[build.log](https://github.com/user-attachments/files/17818657/build.log)

### PR DESCRIPTION
**Pull request by emanuele6**
In C23 (default C standard used by GCC 15), `jv (*fptr)();` has become equivalent to `jv (*fptr)(void);` so we can no longer assign builtin implemenations directly to the `fptr` member of `cfunctions` without generating a compile error.

Since there does not seem to be any straight-forward way to tell autoconf to force the compiler to use C99 short of explicitly adding -std=c99 to CFLAGS, it is probably a cleaner solution to just make the code C23 compatible.

A possible solution could have been to just redeclare `cfunction.fptr` as `void*`, but then the functions' return type would not have been type checked (e.g. if you tried to add a `{printf, "printf", 2}`, where printf is a function that does not return jv, the compiler wouldn't have complained.)

We were already not typechecking the arguments of the functions, so e.g.
```c
{binop_plus, "_plus", 3},  /* instead of {f_plus, "_plus, 3},       */
{f_setpath, "setpath", 4}, /* instead of {f_setpath, "setpath", 3}, */
```
compile without errors despite not having the correct prototype.

So I thought of instead improving the situation by redefining `cfunction.fptr` as a union of function pointers with the prototypes that the jq bytecode interpreter can call, and use a macro to add the builtin functions to `function_list` using to the arity argument to assign the implementation function to the appropriate union member.

Now the code won't compile if the wrong arity, or an arity not supported by the bytecode interpreter (>5 = 1input+4arguments), or a prototype not jallable by the bytecode interpreter (e.g. `binop_plus` that doesn't expect a `jq_state*` argument).

```console
$ make -j
make  all-recursive
make[1]: Entering directory '/home/emanuele6/git/jq'
make[2]: Entering directory '/home/emanuele6/git/jq'
  CC       src/builtin.lo
src/builtin.c:1831:9: error: initialization of 'jv (*)(jq_state *, jv,  jv,  jv,  jv)' from incompatible pointer type 'jv (*)(jq_state *, jv,  jv,  jv)' [-Wincompatible-pointer-types]
 1831 |   CFUNC(f_setpath, "setpath", 4),
      |         ^~~~~~~~~
src/builtin.c:1794:28: note: in definition of macro 'CFUNC'
 1794 |   {.fptr = { .a ## arity = func }, name, arity}
      |                            ^~~~
src/builtin.c:1831:9: note: (near initialization for 'function_list[88].fptr.a4')
 1831 |   CFUNC(f_setpath, "setpath", 4),
      |         ^~~~~~~~~
src/builtin.c:1794:28: note: in definition of macro 'CFUNC'
 1794 |   {.fptr = { .a ## arity = func }, name, arity}
      |                            ^~~~
make[2]: *** [Makefile:1056: src/builtin.lo] Error 1
make[2]: Leaving directory '/home/emanuele6/git/jq'
make[1]: *** [Makefile:1193: all-recursive] Error 1
make[1]: Leaving directory '/home/emanuele6/git/jq'
```
```console
$ make
mkdir -p src
  GEN      src/version.h
make  all-recursive
make[1]: Entering directory '/home/emanuele6/git/jq'
make[2]: Entering directory '/home/emanuele6/git/jq'
  CC       src/main.o
  CC       src/builtin.lo
src/builtin.c:1794:15: error: 'union <anonymous>' has no member named 'a6'; did you mean 'a1'?
 1794 |   {.fptr = { .a ## arity = func }, name, arity}
      |               ^
src/builtin.c:1821:3: note: in expansion of macro 'CFUNC'
 1821 |   CFUNC(f_test6, "test6", 6),
      |   ^~~~~
src/builtin.c:1821:9: error: initialization of 'jv (*)(jq_state *, jv)' from incompatible pointer type 'jv (*)(jq_state *, jv,  jv,  jv,  jv,  jv,  jv)' [-Wincompatible-pointer-types]
 1821 |   CFUNC(f_test6, "test6", 6),
      |         ^~~~~~~
src/builtin.c:1794:28: note: in definition of macro 'CFUNC'
 1794 |   {.fptr = { .a ## arity = func }, name, arity}
      |                            ^~~~
src/builtin.c:1821:9: note: (near initialization for 'function_list[73].fptr.a1')
 1821 |   CFUNC(f_test6, "test6", 6),
      |         ^~~~~~~
src/builtin.c:1794:28: note: in definition of macro 'CFUNC'
 1794 |   {.fptr = { .a ## arity = func }, name, arity}
      |                            ^~~~
make[2]: *** [Makefile:1056: src/builtin.lo] Error 1
make[2]: Leaving directory '/home/emanuele6/git/jq'
make[1]: *** [Makefile:1193: all-recursive] Error 1
make[1]: Leaving directory '/home/emanuele6/git/jq'
make: *** [Makefile:831: all] Error 2
```
```console
$ make
make  all-recursive
make[1]: Entering directory '/home/emanuele6/git/jq'
make[2]: Entering directory '/home/emanuele6/git/jq'
  CC       src/builtin.lo
src/builtin.c:1813:9: error: initialization of 'jv (*)(jq_state *, jv,  jv,  jv)' from incompatible pointer type 'jv (*)(jv,  jv)' [-Wincompatible-pointer-types]
 1813 |   CFUNC(binop_plus, "_plus", 3),
      |         ^~~~~~~~~~
src/builtin.c:1794:28: note: in definition of macro 'CFUNC'
 1794 |   {.fptr = { .a ## arity = func }, name, arity}
      |                            ^~~~
src/builtin.c:1813:9: note: (near initialization for 'function_list[62].fptr.a3')
 1813 |   CFUNC(binop_plus, "_plus", 3),
      |         ^~~~~~~~~~
src/builtin.c:1794:28: note: in definition of macro 'CFUNC'
 1794 |   {.fptr = { .a ## arity = func }, name, arity}
      |                            ^~~~
make[2]: *** [Makefile:1056: src/builtin.lo] Error 1
make[2]: Leaving directory '/home/emanuele6/git/jq'
make[1]: *** [Makefile:1193: all-recursive] Error 1
make[1]: Leaving directory '/home/emanuele6/git/jq'
make: *** [Makefile:831: all] Error 2
```

Also, the code now compiles with gcc -std=c23.

Fixes #3206

### CODE REVIEW

File: src/execute.c [hunk 1]
```diff
@@ -917,11 +917,11 @@ jv jq_next(jq_state *jq) {
...
-      case 3: top = ((jv (*)(jq_state *, jv, jv, jv))function->fptr)(jq, in[0], in[1], in[2]); break;
-      case 4: top = ((jv (*)(jq_state *, jv, jv, jv, jv))function->fptr)(jq, in[0], in[1], in[2], in[3]); break;
-      case 5: top = ((jv (*)(jq_state *, jv, jv, jv, jv, jv))function->fptr)(jq, in[0], in[1], in[2], in[3], in[4]); break;
+      case 1: top = function->fptr.a1(jq, in[0]); break;
+      case 2: top = function->fptr.a2(jq, in[0], in[1]); break;
+      case 3: top = function->fptr.a3(jq, in[0], in[1], in[2]); break;
+      case 4: top = function->fptr.a4(jq, in[0], in[1], in[2], in[3]); break;
+      case 5: top = function->fptr.a5(jq, in[0], in[1], in[2], in[3], in[4]); break;
       // FIXME: a) up to 7 arguments (input + 6), b) should assert
       // because the compiler should not generate this error.
```
Comment (wader) [inline src/execute.c]: Unrelated to this PR: is the numbers in this comment outdated? should say "up to 5 (input + 4)"? and is `MAX_CFUNCTION_ARGS` constant a bit weirdly named? is more a constant that is at least equal or more than what max c-builtins arity is?

**Comment by wader** [comment]
Would it make sense to have CI pipeline that builds with highest supported C standard version?

**Review by wader — APPROVED** [review]

File: src/execute.c (hunk 1 above)
Comment (emanuele6) [reply src/execute.c]: I also noticed the `MAX_CFUNCTION_ARGS` set to 10, but I have not checked what it does

Comment (wader) [reply src/execute.c]: Seems to only be used when declaring the local `cfunc_input` array.

Comment (emanuele6) [reply src/execute.c]: Yeah, which is really just the same as the `in` used by those function calls.
The buffer is declared at the start of the `jq_next` function for some reason even though it is only used by `CALL_BUILTIN`; I will clean that up

Comment (emanuele6) [reply src/execute.c]: I set `MAX_CFUNCTION_ARGS` to 4, removed `cfunction.fptr.a5` since it was not used, and removed a bunch of unnecessary roundabout code from CALL_BUILTIN

Comment (wader) [reply src/execute.c]: Nice 👍

**Review by wader — APPROVED** [review]
