### PR TITLE
builtin.c: fix build with -Woverlength-strings

### LINKED ISSUE #1481: builtin.inc exceeds maximum length for C99
In order to publish my bindings I need to solve this compiler warning:

```
Found the following significant warnings:
  jq/builtin.inc:1:1: warning: string literal of length 14491 exceeds maximum length 4095 that ISO C99 compilers are required to support [-Woverlength-strings]
```

Is there a way to split this literal into smaller chunks or so?

### PR DESCRIPTION
**Pull request by emanuele6**
C99 only allows string literals long at most 4095 characters.
`jq_builtins` was a lot longer than that.

I rewrote all the optional libm error stubs in C so the value of `jq_builtins` is not build dependent.

I replaced the command that generates builtin.inc with a POSIX compliant od|sed command that encodes builtin.jq as a comma delimited list of octal numbers (that can be embedded in C using a `{}` literal).

I also added `-Woverlength-strings` to `AM_CFLAGS` to verify that the problem is fixed.

Fixes #1481

### CODE REVIEW

File: src/builtin.c [hunk 1]
```diff
@@ -226,6 +242,11 @@ static jv f_frexp(jq_state *jq, jv input) {
   jv_free(input);
   return ret;
 }
+#else
+static jv f_frexp(jq_state *jq, jv input) {
+  jv error = jv_string("Error: frexp/0 not found at build time");
+  return ret_error(input, error);
+}
```
Comment (wader) [inline src/builtin.c]: Worth adding some `LIBM_DD` macro thingy for functions that return array? maybe messy to make such macro generic?

File: src/builtin.c [hunk 2]
```diff
@@ -1672,27 +1703,21 @@ static jv f_current_line(jq_state *jq, jv a) {
 
 #define LIBM_DD(name) \
   {f_ ## name,  #name, 1},
-#define LIBM_DD_NO(name)
+#define LIBM_DD_NO(name) LIBM_DD(name)
```
Comment (wader) [inline src/builtin.c:1675]: This took longer to understand that i want to admit :) too early here

**Review by wader — APPROVED** [review]

File: Makefile.am [hunk 3]
```diff
@@ -119,7 +120,12 @@ src/main.c: src/version.h src/config_opts.inc
 
 src/builtin.inc: $(srcdir)/src/builtin.jq
 	mkdir -p src
-	$(AM_V_GEN) sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/"/' -e 's/$$/\\n"/' $(srcdir)/src/builtin.jq > $@
+	$(AM_V_GEN) od -vAn -to1 -- $< | \
+	sed -e 's/$$/ /' \
+	    -e 's/\([0123456789]\)\( \)/\1, /g' \
```
Comment (emanuele6) [inline Makefile.am]: `\( \)` can be just ` `.

File: src/builtin.c (hunk 2 above)
Comment (emanuele6) [reply src/builtin.c:1675]: ^^

File: src/builtin.c (hunk 1 above)
Comment (emanuele6) [reply src/builtin.c]: Sure, why not

File: src/builtin.c [hunk 4]
```diff
@@ -199,14 +208,40 @@ static jv f_ ## name(jq_state *jq, jv input, jv a, jv b, jv c) { \
...
+static jv f_ ## name(jq_state *jq, jv input) { \
+  if (jv_get_kind(input) != JV_KIND_NUMBER) { \
+    return type_error(input, "number required"); \
+  } \
+  type value; \
+  double d = name(jv_number_value(input), &value); \
+  jv ret = JV_ARRAY(jv_number(d), jv_number(value)); \
+  jv_free(input); \
+  return ret; \
+}
```
Comment (wader) [inline src/builtin.c:229]: Neat 📸

**Review by wader — APPROVED** [review]

File: src/libm.h [hunk 5]
```diff
@@ -289,3 +289,18 @@ LIBM_DDD(ldexp)
...
 #endif
+#ifdef HAVE_MODF
+LIBM_DA(modf, double)
+#else
+LIBM_DA_NO(modf, double)
+#endif
+#ifdef HAVE_FREXP
+LIBM_DA(frexp, int)
+#else
+LIBM_DA_NO(frex, int)
```
Comment (emanuele6) [inline src/libm.h]: typo

**Review by wader — APPROVED** [review]

File: src/builtin.c [hunk 6]
```diff
@@ -1671,28 +1671,24 @@ static jv f_current_line(jq_state *jq, jv a) {
...
 #include "libm.h"
-#ifdef HAVE_FREXP
   {f_frexp,"frexp", 1},
-#endif
-#ifdef HAVE_MODF
   {f_modf,"modf", 1},
-#endif
-#ifdef HAVE_LGAMMA_R
   {f_lgamma_r,"lgamma_r", 1},
-#endif
```
Comment (emanuele6) [inline src/builtin.c]: Those can be removed now; the macro adds them automatically, so there were doubled entries.

File: Makefile.am [hunk 7]
```diff
@@ -119,7 +120,12 @@ src/main.c: src/version.h src/config_opts.inc
 
 src/builtin.inc: $(srcdir)/src/builtin.jq
 	mkdir -p src
-	$(AM_V_GEN) sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/"/' -e 's/$$/\\n"/' $(srcdir)/src/builtin.jq > $@
+	$(AM_V_GEN) od -v -A n -t o1 -- $< | \
+	sed -e 's/$$/ /' \
```
Comment (nicowilliams) [inline Makefile.am:124]: lol

Comment (emanuele6) [reply Makefile.am:124]: 😎

**Comment by nicowilliams** [comment]
LGTM!
