### PR TITLE
Use codepoint index for indices/1, index/1 and rindex/1

### LINKED ISSUE #1430: index() function returns wrong offset for non-ascii chars
I'm trying to strip away some text from part of a text. Trying to use something like `sub("!.*"; "")` doesn't work, as it is giving me a Segmentation fault when text is too long. So I tried to go this route:

`$ jq '.msg | .[0:index("!")]'`

which works fine with input like:
`{"msg": "hello world!"}
`
but fails when text contains wide characters:
`{"msg": "здравствуй мир!"}
`
```
$ echo '{"msg": "здравствуй мир!"}' | jq '.msg | index("!")'
27
```

```
$ echo '{"msg": "hello world!"}' | jq '.msg | index("!")'
11
```
```
$ jq --version
jq-1.5
$ uname -a
Darwin atschabu-C02SF0UTG8WM 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
```

### LINKED ISSUE #1624: substring of index/rindex doesn't work for utf8 inputs
```
echo  '正xyz' | jq -Rsr '.[:rindex("x")]'
正xy
while it should output:
正
```
It seems substring thinks length(正xy)==3 
but rindex thinks length(正xy)==5
this issue make jsonp parse example in FAQ fails for utf8 inputs

```
Q: How can I convert JSON-P (JSONP) to JSON using jq?
A: Assuming that the padding takes the form of a function call:
$ jq -s -R  '.[1+index("("): rindex(")")] | fromjson'
```

### LINKED ISSUE #3064: `indices` reports byte offsets instead of character offsets
**Describe the bug**
jq uses _characters_ to index strings.
To see that, we can run `"🇬🇧oo" | .[0 : 1,2,3,4]`, which yields "🇬" "🇬🇧" "🇬🇧o" "🇬🇧oo".
Note that 🇬🇧 is actually two characters and 8 bytes, as we can see from `"🇬🇧" | length, utf8bytelength`.
However, the `indices` filter returns _byte offsets_  to the pattern in the string.
The documentation does not specify the behaviour of `indices` for UTF-8 strings, but given that `length` and `.[x:y]` use character counts to index strings, it is likely that this is a bug and not just undocumented behaviour.

**To Reproduce**
$ ./jq-linux-amd64-1.7.1 -nc '"🇬🇧oo" | indices("o")'
[8,9]
$ ./jq-linux-amd64-1.7.1 -nc '"ƒoo" | indices("o")'
[2,3]

**Expected behavior**
$ ./jq-linux-amd64-1.7.1-fixed -nc '"🇬🇧oo" | indices("o")'
[2,3]
$ ./jq-linux-amd64-1.7.1-fixed -nc '"ƒoo" | indices("o")'
[1,2]

The problem is probably caused in [jv_string_indexes](https://github.com/jqlang/jq/blob/c95b34ff827d05a2d262f00280a4891a295ed0ed/src/jv.c#L1272).

### PR DESCRIPTION
**Pull request by wader**
Previsouly byte index was used.

Fixes #1430, fixes #1624, fixes #3064.

### CODE REVIEW

File: src/jv.c [hunk 1]
```diff
@@ -1274,15 +1274,21 @@ jv jv_string_indexes(jv j, jv k) {
...
   int idxlen = jv_string_length_bytes(jv_copy(k));
   jv a = jv_array();
 
   if (idxlen != 0) {
-    p = jstr;
+    int n = 0;
+    p = lp = jstr;
     while ((p = _jq_memmem(p, (jstr + jlen) - p, idxstr, idxlen)) != NULL) {
-      a = jv_array_append(a, jv_number(p - jstr));
+      while (lp < p) {
```
Comment (wader) [inline src/jv.c:1286]: To make this even more efficient i guess we would need to count codepoints inside memmem somehow

**Comment by wader** [comment]
Haven't entirely convinced myself yet that it should be fine to look for matches using the byte representation. Assuming both the needle and haystack is valid utf-8 i'm thinking it should be fine because of utf-8's self-synchronization property.

Update: now looking at `jv_string_slice` https://github.com/jqlang/jq/blob/c95b34ff827d05a2d262f00280a4891a295ed0ed/src/jv.c#L1374 i'm not sure anymore if one can assume strings are valid utf-8 or is the invalid utf-8 checks not really needed?

**Review by emanuele6 — APPROVED** [review]

**Comment by itchyny** [comment]
I'd like to include this. Any objection on changing the behavior in 1.8?

**Comment by wader** [comment]
Ok to merge for me but would be great if someone could have a look or know if my assumption about strings always being valid utf-8 is true.

**Comment by pkoppstein** [comment]
@itchyny asked:

> Any objection on changing the behavior in 1.8

This is a major breaking change and it has been my understanding for some years that such changes would have to wait until jq 2.0.  Certainly if we were following a strict SemVer policy that would be the case.  Since we don't seem to be doing so, the situation is not black-and-white, but if the change is incorporated into 1.8, we should be sure to highlight it.   

@wader wrote:
> if my assumption about strings always being valid utf-8 is true.

Based on past experience, such an assumption would not be warranted, so the question is: could the proposed changes make anything worse?  I suppose the major issue would be whether (in the presence of invalid utf-8) the old index would give an accurate byte count but the new version might give an inaccurate codepoint count. 

Perhaps a starting point would be `"a\uDD1Ec"`:
```
echo '"a\uDD1Ec"' | jaq -r .
Error: failed to parse: invalid character with index 56606

echo '"a\uDD1Ec"' | jq -c '[index("c"), length]'
[4,3]
```

**Comment by wader** [comment]
> @itchyny asked:
> 
> > Any objection on changing the behavior in 1.8
> 
> This is a major breaking change and it has been my understanding for some years that such changes would have to wait until jq 2.0. Certainly if we were following a strict SemVer policy that would be the case. Since we don't seem to be doing so, the situation is not black-and-white, but if the change is incorporated into 1.8, we should be sure to highlight it.

I can't see how the current behaviour for non-ASCII strings makes any sense or could even be useful in any resonable way? so for me it feels more like a bug.

> @wader wrote:
> 
> > if my assumption about strings always being valid utf-8 is true.
> 
> Based on past experience, such an assumption would not be warranted, so the question is: could the proposed changes make anything worse? I suppose the major issue would be whether (in the presence of invalid utf-8) the old index would give an accurate byte count but the new version might give an inaccurate codepoint count.
> 
> Perhaps a starting point would be `"a\uDD1Ec"`:
> 
> ```
> echo '"a\uDD1Ec"' | jaq -r .
> Error: failed to parse: invalid character with index 56606
> 
> echo '"a\uDD1Ec"' | jq -c '[index("c"), length]'
> [4,3]
> ```

This is an incomplete surrogates pair? yeap stuff like this i'm concerned about also.

**Comment by pkoppstein** [comment]
@wader wrote:

> I can't see how the current behaviour for non-ASCII strings makes any sense or could even be useful in any reasonable way?

Currently:
```
echo '"a\udc37c"' | jq -c '[., length, index("\udc37")]'
["a�c",3,1]
```
With the proposed change, would this result be different?

In any case, as I've said, as far as I'm concerned, the main thing is that if the change is made in 1.8, it should be highlighted, preferably as a possibly "breaking" change.

**Comment by wader** [comment]
With this change:
```sh
$ echo '"a\uDD1Ec"' | ./jq -c '[index("c"), length]'
[2,3]
```
Seems correct assuming broken surrogates codepoints should be allowed. But I think i'm mostly concern if there is any way to produce jq strings that has a byte buffer that is not valid utf-8. If so use of `jvp_utf8_decode_length` might end up out-of-sync codepoint-wise or pointing outside the byte buffer.

**Review by itchyny — APPROVED** [review]

**Comment by wader** [comment]
As @nicowilliams also expressed this is a bug https://github.com/jqlang/jq/issues/1430#issuecomment-347628258 ill merge this now

**Comment by thaliaarchi** [comment]
Should the docs be updated to make it clear that it's a codepoint index, instead of byte index?

**Comment by wader** [comment]
Good point, i did quick skimming of the docs and it seems like we don't say it's byte offset anywhere but we don't make it that clear that it's codepoints either. So maybe mention for the index-functions and possible also under "Array/String Slice" and/or "Types and Values"? for the regexp functions we do mention things are in codepoints.
