### PR TITLE
Fix halt_error to print message without prefix in raw mode (fix #1902)

### LINKED ISSUE #1902: halt_error prints "jq: error:" in master
**Describe the bug**

In MSYS2 nightly builds `halt_error` prints "jq: error:" before any output. Can "jq: error:" be removed from output? The 1.6 release build from the official MSYS2 package repo doesn't print "jq: error:", and niether do the Linux builds.

**To Reproduce**

1. Download a Windows nightly.
2. `jq -n '"test" | halt_error(1)'`

```sh
$ nightly/win64/jq --version
jq-1.6-94-gaaf200f
$ nightly/win64/jq.exe -n '"test" | halt_error(1)'   # wrong: extra "jq: error: "
jq: error: test                                 
```

**Expected behavior**

```sh
$ /mingw64/nightly/jq --version
jq-1.6
$ /mingw64/bin/jq -n '"test" | halt_error(1)'    # expected output: next line
test                                            
```

**Environment (please complete the following information):**

 - Windows 10 Enterprise x64
 - jq-1.6-94-gaaf200f 2019-05-12

### PR DESCRIPTION
**Pull request by itchyny**
This PR fixes #1902. The manual says that `halt_error` should print the input with no decoration . This is a regression of 2b4d51f6976f15307e70387d3e015de274589193, which is after 1.6.

### CODE REVIEW

**Review by wader — APPROVED** [review]

**Comment by wader** [comment]
This got me thinking if we want `halt_error` to be able to output raw strings? ex:
```sh
$ jq -rn '"a\u0000b" | halt_error' 2>&1 | hexdump -C
00000000  6a 71 3a 20 65 72 72 6f  72 3a 20 61              |jq: error: a|
0000000c
$ jq -rn '"a\u0000b"' | hexdump -C
00000000  61 00 62 0a                                       |a.b.|
00000004
```

**Comment by itchyny** [comment]
@wader Good catch, let's do so. The manual says `as raw output`.

File: src/main.c [hunk 1]
```diff
@@ -216,12 +216,14 @@ static int process(jq_state *jq, jv value, int flags, int dumpopts) {
     jv_free(exit_code);
     jv error_message = jq_get_error_message(jq);
     if (jv_get_kind(error_message) == JV_KIND_STRING) {
-      fprintf(stderr, "jq: error: %s", jv_string_value(error_message));
+      // No prefix should be added to the output of `halt_error`.
+      fwrite(jv_string_value(error_message), 1,
+          jv_string_length_bytes(jv_copy(error_message)), stderr);
```
Comment (wader) [inline src/main.c:221]: I guess we don't leak the `jv` copy here as `jv_string_length_bytes` free/unref? I will have to read up on how the ownership works for the `jv` type and functions, eg why does `jv_string_value` not free/unref?

**Review by wader — APPROVED** [review]

**Comment by wader** [comment]
@itchyny 👍 good catch on notice the manual say raw string

File: tests/shtest [hunk 2]
```diff
@@ -275,11 +275,19 @@ if [ -n "$($VALGRIND $Q $JQ -n 'halt_error(1)' 2>&1)" ]; then
...
     exit 1
 fi
-if [ "$($VALGRIND $Q $JQ -n '"xyz\n"|halt_error(1)' 2>&1)" != "jq: error: xyz" ]; then
+if [ "$($VALGRIND $Q $JQ -n '"xy" | halt_error(1)' 2>&1 || echo "z")" != "xyz" ]; then
+    echo "jq halt_error(1) had unexpected output" 1>&2
+    exit 1
+fi
+if [ "$($VALGRIND $Q $JQ -n '"x\u0000y\u0000z" | halt_error(1)' 2>&1)" != "$(printf 'x\x00y\x00z')" ]; then
+    echo "jq halt_error(1) had unexpected output" 1>&2
+    exit 1
```
Comment (wader) [inline tests/shtest:288]: Seems linux build is not happy about this:
```
+ /home/runner/work/jq/jq/tests/../jq -n halt_error(1)
+ [ 1 -ne 1 ]
+ /home/runner/work/jq/jq/tests/../jq -n halt_error(11)
+ [ 11 -ne 11 ]
+ /home/runner/work/jq/jq/tests/../jq -n halt_error(1)
+ [ -n  ]
+ /home/runner/work/jq/jq/tests/../jq -n "xyz\n" | halt_error(1)
+ [ -n  ]
+ /home/runner/work/jq/jq/tests/../jq -n "xy" | halt_error(1)
+ echo z
+ [ xyz != xyz ]
+ /home/runner/work/jq/jq/tests/../jq -n "x\u0000y\u0000z" | halt_error(1)
+ printf x\x00y\x00z
+ [ xyz != x\x00y\x00z ]
+ echo jq halt_error(1) had unexpected output
jq halt_error(1) had unexpected output
+ exit 1
```
Hmm zero bytes gone from LHS value? shell doing something?

Comment (itchyny) [reply tests/shtest:288]: Yeah, NUL bytes are trimmed in command substitution.

Comment (wader) [reply tests/shtest:288]: Aha, any idea why macOS build was fine?

**Review by wader — APPROVED** [review]

File: tests/shtest (hunk 2 above)
Comment (itchyny) [reply tests/shtest:288]: bash is old. It passes if Bash is 3.

**Comment by itchyny** [comment]
Thank you.

File: tests/shtest (hunk 2 above)
Comment (wader) [reply tests/shtest:288]: 👍 that explains things, great work!

Comment (emanuele6) [reply tests/shtest:288]: If necessary, `\0` can be used instead of `\x00`. That would work in any version bash or POSIX-compliant shell.
