### PR TITLE
fix: preserve numerical precision on unary negation

### LINKED ISSUE #2704: bug: preservation of literal numbers
The literal representation of certain negative numbers is not being properly preserved.
 
Consider:
```
./jq --version
jq-1.6-268-gc99981c-dirty

./jq -nM '1E1000'
1E+1000

./jq -nM '-1E1000'
-1.7976931348623157e+308 # !!!

./jq -nM '100000000000000000000000000000002'
100000000000000000000000000000002

./jq -nM '-100000000000000000000000000000002'
-1e+32 # !!!

```

Platform: Mac OS

### PR DESCRIPTION
**Pull request by itchyny**
This commit fixes #2704.
```
 $ ./jq -n '[1234567890987654321,-1234567890987654321 | tojson]'
[
  "1234567890987654321",
  "-1234567890987654321"
]
```

### CODE REVIEW

File: src/jv.c [hunk 1]
```diff
@@ -571,19 +570,18 @@ static jvp_literal_number* jvp_literal_number_alloc(unsigned literal_length) {
     + sizeof(decNumberUnit) * units
   );
 
+  n->refcnt = JV_REFCNT_INIT;
+  n->num_double = NAN;
+  n->literal_data = NULL;
```
Comment (wader) [inline src/jv.c:575]: What was the reson to move this from new to alloc?

Looks like `jvp_literal_number_new` is the only user of `jvp_literal_number_alloc`, maybe could be merged or keep separate for readability?

**Comment by wader** [comment]
Nice! have some vague memory of trying to fix this just for constant literals by changing the lexer to include the `-` in the literal but got messy for some reason

File: src/jv.c (hunk 1 above)
Comment (itchyny) [reply src/jv.c:575]: Also used for negate.

Comment (wader) [reply src/jv.c:575]: Aha sorry 👍

**Review by wader — APPROVED** [review]

**Comment by itchyny** [comment]
Thank you!
